### ISSUE TITLE
Not working with phonegap 8.0

### ISSUE THREAD

**Issue by FreddyCrugger** [dpa99c/cordova-check-plugins#29]
Hello,

I cannot get it to work with Phonegap 8.0

I am using the nose.js command prompt in windows 10 64bit.

 Running this command:
cordova-check-plugins --update=auto --force

It looks like it is working but none of the package.json files or config.xml have the new versions of each core plugin:

I can run your command many times, it will still shows the old to new versions.

Updated 'cordova-plugin-whitelist' from 1.2.2 to 1.3.3
Updated 'cordova-plugin-vibration' from 2.1.6 to 3.0.1
Updated 'cordova-plugin-statusbar' from 2.1.3 to 2.4.1
Updated 'cordova-plugin-splashscreen' from 3.2.2 to 5.0.2
Updated 'cordova-plugin-network-information' from 1.2.1 to 2.0.1
Updated 'cordova-plugin-media' from 2.2.0 to 5.0.2
Updated 'cordova-plugin-inappbrowser' from 1.3.0 to 2.0.2
Updated 'cordova-plugin-geolocation' from 2.1.0 to 4.0.1
Updated 'cordova-plugin-file-transfer' from 1.5.1 to 1.7.1
Updated 'cordova-plugin-dialogs' from 1.2.1 to 2.0.1
Updated 'cordova-plugin-device-orientation' from 1.0.7 to 2.0.0
Updated 'cordova-plugin-device-motion' from 1.2.5 to 2.0.0
Updated 'cordova-plugin-device' from 1.1.7 to 2.0.1
Updated 'cordova-plugin-contacts' from 2.0.1 to 3.0.1
Updated 'cordova-plugin-console' from 1.0.7 to 1.1.0
Updated 'cordova-plugin-media-capture' from 1.2.0 to 3.0.1
Updated 'cordova-plugin-camera' from 2.1.1 to 4.0.2
Updated 'cordova-plugin-battery-status' from 1.1.2 to 2.0.1

Automatically updated all outdated plugins

C:\laragon\www\android>

Any idea why please?

Thank you.

**Comment by dpa99c** [comment]
I just tested `cordova-check-plugins@4.0.2` with `phonegap@8.0.0` CLI on Windows 10 and it seems to work fine - see console output below.

Please run the same series of commands as below in the console output to confirm this also works in your dev environment.

If the issue you're having is with a specific Cordova project, please run `cordova-check-plugins --update=auto --verbose --debug` and post the full console output.



<details>
<summary>console output</summary>

```

Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

D:\Temp>phonegap -v
8.0.0

D:\Temp>cordova -v
'cordova' is not recognized as an internal or external command, operable program or batch file.

D:\Temp>node -v
v7.10.0

D:\Temp>npm -v
4.2.0

D:\Temp>phonegap create test && cd test
Creating a new cordova project.

D:\Temp\test>phonegap plugin add cordova-plugin-whitelist
Saved plugin info for "cordova-plugin-whitelist" to config.xml

D:\Temp\test>phonegap plugin ls
cordova-plugin-whitelist 1.3.3 "Whitelist"

D:\Temp\test>more config.xml | grep whitelist
    <plugin name="cordova-plugin-whitelist" spec="^1.3.3" />

D:\Temp\test>more package.json | grep whitelist
    "cordova-plugin-whitelist": "^1.3.3"
      "cordova-plugin-whitelist": {}


# Fake an earlier plugin version

D:\Temp\test>powershell -Command "(gc config.xml) -replace '1.3.3', '1.0.0' | Out-File -encoding ASCII config.xml"

D:\Temp\test>more config.xml | grep whitelist
    <plugin name="cordova-plugin-whitelist" spec="^1.0.0" />

D:\Temp\test>powershell -Command "(gc package.json) -replace '1.3.3', '1.0.0' | Out-File -encoding ASCII package.json"

D:\Temp\test>more package.json | grep whitelist
    "cordova-plugin-whitelist": "^1.0.0"
      "cordova-plugin-whitelist": {}

D:\Temp\test>powershell -Command "(gc plugins\cordova-plugin-whitelist\plugin.xml) -replace '1.3.3', '1.0.0' | Out-File -encoding ASCII plugins\cordova-plugin-whitelist\plugin.xml"

D:\Temp\test>phonegap plugin ls
cordova-plugin-whitelist 1.0.0 "Whitelist"

# Update using cordova-check-plugins with phonegap@8.0.0

D:\Temp\test>cordova-check-plugins -v
4.0.2

D:\Temp\test>cordova-check-plugins --update=auto --verbose --debug
Running cordova-check-plugins...
Verbose output enabled
cwd is: D:\Temp\test
Finding installed plugins
Reading installed plugin versions
Checking latest npm registry version for 'cordova-plugin-whitelist' using 'cordova-plugin-whitelist@^1.3.3'
DEBUG: npm view "cordova-plugin-whitelist@^1.3.3" version
Checking remote versions... |Retrieved latest npm registry version for 'cordova-plugin-whitelist

***************************
* Plugin update available *
***************************

plugin: cordova-plugin-whitelist
source: npm://cordova-plugin-whitelist@^1.3.3
installed version: 1.0.0
remote version: 1.3.3

Updating plugins: cordova-plugin-whitelist


Updating 'cordova-plugin-whitelist'... /local cordova command not found - checking for global cordova.

Error: Command failed: node node_modules/cordova/bin/cordova -v
module.js:472
    throw err;
    ^

Error: Cannot find module 'D:\Temp\test\node_modules\cordova\bin\cordova'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3

Updating 'cordova-plugin-whitelist'... -global cordova command not found - checking for global phonegap.

Error: Command failed: cordova -v
'cordova' is not recognized as an internal or external command,
operable program or batch file.

Updating 'cordova-plugin-whitelist'... /local cordova command not found - checking for global cordova.

Error: Command failed: node node_modules/cordova/bin/cordova -v
module.js:472
    throw err;
    ^

Error: Cannot find module 'D:\Temp\test\node_modules\cordova\bin\cordova'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3

Updating 'cordova-plugin-whitelist'... -global cordova command not found - checking for global phonegap.

Error: Command failed: cordova -v
'cordova' is not recognized as an internal or external command,
operable program or batch file.

Updating 'cordova-plugin-whitelist'... \Removed plugin 'cordova-plugin-whitelist'
Update command: phonegap plugin add cordova-plugin-whitelist@^1.3.3 --save --fetch
Updating 'cordova-plugin-whitelist'... \Re-added plugin 'cordova-plugin-whitelist'

Updated 'cordova-plugin-whitelist' from 1.0.0 to 1.3.3

Automatically updated all outdated plugins

D:\Temp\test>phonegap plugin ls
cordova-plugin-whitelist 1.3.3 "Whitelist"

D:\Temp\test>more config.xml | grep whitelist
    <plugin name="cordova-plugin-whitelist" spec="^1.3.3" />

D:\Temp\test>more package.json | grep whitelist
    "cordova-plugin-whitelist": "^1.3.3"
      "cordova-plugin-whitelist": {}

```

</details>

**Comment by dpa99c** [comment]
Closed due to no response from OP
